hlxsites/bitdefender

- blocks/header/header.js
- package-lock.json
- scripts/scripts.js
Fix #1 
Test URLs:
- After: https://1-allow-iso-language-codes-in-urls--bitdefender--hlxsites.hlx.page/en-au/solutions/
> Allow iso language codes in urls

- blocks/button/button.css
- blocks/button/button.js
- scripts/scripts.js
- styles/lazy-styles.css
- styles/styles.css
Fix #10
I did not implement the "X" button in top/right corner. this will come after @johan-t merged the [header PR](https://github.com/hlxsites/bitdefender/pull/12), which will introduce the css for the "X".
Test URLs:
- After: https://10-download-button-modal--bitdefender--hlxsites.hlx.page/en-au/solutions/
> feat: Download Button with modal overlay

- blocks/footer/footer.css
- blocks/footer/footer.js
- icons/black_down_arrow.svg
Fix #5 
Tablet/Mobile
Desktop
Large Desktop
Test URLs:
- After: https://build-footer-mobile-first--bitdefender--hlxsites.hlx.page/en-au/solutions/
> Build footer mobile first

- blocks/footer/footer.css
- icons/black_down_arrow.svg
Fix #33 
Test URLs:
- After: https://use-built-arrow-in-footer--bitdefender--hlxsites.hlx.page/en-au/solutions/
> Changed from arrow svg to arrow css

- blocks/hero/hero.js
- scripts/scripts.js
Fix #48 
Test URLs:
- After: https://48-refactor-buildheroblock--bitdefender--hlxsites.hlx.page/en-au/solutions/
> Refactor buildHero

- blocks/accordion/accordion.css
- blocks/columns/columns.css
- blocks/hero/hero.css
- blocks/sticky-navigation/sticky-navigation.css
- styles/styles.css
Fix #46
Test URLs:
- After: https://46-center-sections--bitdefender--hlxsites.hlx.page/en-au/solutions/
> feat: centre body and sections

- blocks/header/header.css
- styles/styles.css
I had to change some of the header positions because they were messed up 
Test URLs:
- After: https://font-change--bitdefender--hlxsites.hlx.page/en-au/solutions/
> fixed font problems

- scripts/delayed.js
- scripts/scripts.js
Fix #38
Test URLs:
- After: https://38-martech-integration--bitdefender--hlxsites.hlx.page/en-au/solutions/
> feat: martech integration

- .github/pull_request_template.md
- scripts/delayed.js
- scripts/scripts.js
Test URLs:
- After: https://remove-localisation--bitdefender--hlxsites.hlx.page/solutions/
> feat: remove localisation in URL

- blocks/accordion/accordion.css
- styles/styles.css
Fix #71 
Test URLs:
- After: https://global-styling--bitdefender--hlxsites.hlx.page/solutions/
> Initial global styling

- blocks/columns/columns.css
- styles/styles.css
Fix #65
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/drafts/scoman/image-list
- After: https://feat-awards--bitdefender--hlxsites.hlx.page/drafts/scoman/image-list
> Awards columns 

- blocks/header/header.css
- blocks/header/header.js
- blocks/hero/hero.css
- blocks/hero/hero.js
- scripts/lib-franklin.js
- styles/lazy-styles.css
Fix #77 
Test URLs:
- After: https://77-apply-styling-to-hero--bitdefender--hlxsites.hlx.page/solutions/
> 77 apply styling to hero

- blocks/quote-carousel/quote-carousel.css
Fix 
Fix #81 
Test URLs:
- After: https://carousel-style-fix--bitdefender--hlxsites.hlx.page/solutions/internet-security
> Fix carousel dots style

- blocks/header/header.css
- styles/styles.css
Fix #98
Test URLs:
- After: https://98-buttons-styling--bitdefender--hlxsites.hlx.page/solutions/
> Fix generic style of buttons link

- blocks/hero/hero.css
- scripts/lib-franklin.js
Fix #103
Test URLs:
- After: https://103-fix-button-arrow-hero--bitdefender--hlxsites.hlx.page/solutions/internet-security
> Fix Choose Your Plan btn

- blocks/sticky-navigation/sticky-navigation.css
Fix #100
Test URLs:
- After: https://100-sticky-nav-fix--bitdefender--hlxsites.hlx.page/solutions/internet-security
> Sticky Navigation fix

- styles/styles.css
Test URLs:
- After: https://fix-centered-section--bitdefender--hlxsites.hlx.page/solutions/
> fix: centered section wide

- blocks/hero/hero.css
Fix #109 
Test URLs:
- After: https://109-fix-download-free-btn--bitdefender--hlxsites.hlx.page/solutions/internet-security
> Fix hero download link alignment

- blocks/barchart/barchart.css
Test URLs:
- After: https://fix-barchat-css--bitdefender--hlxsites.hlx.page/solutions/
> fix barchart list styles

- blocks/features/features.css
- blocks/features/features.js
- icons/tabs_arrow.svg
- scripts/scripts.js
- styles/styles.css
Fix #67
Test URLs:
- After: https://feat-features--bitdefender--hlxsites.hlx.page/drafts/scoman/features
> Columns with tabular data

- blocks/accordion/accordion.css
- blocks/columns/columns.css
- blocks/product-comparison-table/product-comparison-table.css
- blocks/products/products.css
- styles/styles.css
Test URLs:
- After: https://fix-section-wide--bitdefender--hlxsites.hlx.page/solutions/
> fix section wide background with multiple children

- blocks/hero/hero.js
Fix #131 
Test URLs:
- After: https://131-hero-section-ff--bitdefender--hlxsites.hlx.page/solutions/
> Fix hero section images

- blocks/header/header.css
Fix #106 
Test URLs:
- After: https://106-mm-bottom-links--bitdefender--hlxsites.hlx.page/solutions/
> Fix header menu bottom links

- blocks/features/features.js
Fix #134
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android
- After: https://bugfix-featurestag--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android
> Fixed tags in feature names

- styles/styles.css
Fix #127 
Test URLs:
- After: https://127-styling-of-centered-section--bitdefender--hlxsites.hlx.page/solutions/
> fix: styling of centered section

- styles/styles.css
Fix #136 
Test URLs:
- After: https://136-terms-of-use-section--bitdefender--hlxsites.hlx.page/solutions/
> Fix terms of use section

- blocks/quote-carousel/quote-carousel.js
Fix #132 
Test URLs:
- After: https://132-quote-carousel-bug--bitdefender--hlxsites.hlx.page/solutions/internet-security
> Fix carousel on FF

- blocks/accordion/accordion.css
- styles/styles.css
Fix #135 
Test URLs:
- After: https://135-system-requirements-bug--bitdefender--hlxsites.hlx.page/solutions/internet-security
> Fix System Requirement section

- blocks/products/products.css
Fix #169 
Test URLs:
- After: https://169-a11y-featured-products--bitdefender--hlxsites.hlx.page/solutions/
> fix: satisfy A11y (LHS)

- blocks/accordion/accordion.js
Fix #180
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/drafts/scoman/sysreq
- After: https://feat-accordion-first-open--bitdefender--hlxsites.hlx.page/drafts/scoman/sysreq
> First item open variant

- scripts/scripts.js
after: https://fix-tags--bitdefender--hlxsites.hlx.page/solutions/
> removed comments of decorate tags

- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
Fix #84 
Test URLs:
- After: https://feat-tabs--bitdefender--hlxsites.hlx.page/drafts/scoman/tabs
> Tabs block

- blocks/features/features.css
Fix #172 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/drafts/scoman/features
- After: https://bugfix-two-col-features-based-on-main--bitdefender--hlxsites.hlx.page/drafts/scoman/features
> Fixed layout of two column features

- blocks/header/header.css
Test URLs:
- After: https://header-text-align-fix--bitdefender--hlxsites.hlx.page/solutions/
> fixed pos of premium security

- blocks/columns/columns.css
- blocks/hero/hero.css
- blocks/image-columns/image-columns.css
- styles/styles.css
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/free
- After: https://free-migration--bitdefender--hlxsites.hlx.page/solutions/free
> Small fixes for free page migration

- blocks/hero/hero.css
- blocks/image-columns/image-columns.css
- blocks/products/products.css
- styles/styles.css
Fix #245 
Fix #244 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/free
- After: https://main--bitdefender--hlxsites.hlx.page/solutions/
> added pure css checkmark

- blocks/columns/columns.css
- blocks/columns/columns.js
Fix #234 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/vpn
- After: https://big-image-column--bitdefender--hlxsites.hlx.page/solutions/vpn
> Columns text over image variation

- .github/workflows/main.yml
Add Ghost Inspector Tests
Test URLs:
- After: https://ghost-inspector-tests--bitdefender--hlxsites.hlx.page/solutions/
> Add Ghost Inspector Action

- .github/workflows/main.yml
Test URLs:
- After: https://ghost-inspector-branch-name-variable--bitdefender--hlxsites.hlx.page/solutions/
> Enable to run multiple tests

- scripts/delayed.js
- scripts/scripts.js
Fix #185
Test URLs:
- After: https://185-page-metadata-datalayer--bitdefender--hlxsites.hlx.page/solutions/
> feat: add page metadata to datalayer

- blocks/hero/hero.js
Test URLs:
- After: https://fix-discount-hero--bitdefender--hlxsites.hlx.page/solutions/
> migrate to discount nanoblock

- blocks/header/header.css
- blocks/header/header.js
Fix #34
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/mobile-security-ios
- After: https://feat-nav-compare--bitdefender--hlxsites.hlx.page/solutions/mobile-security-ios
> Added compare button

- blocks/columns/columns.css
- styles/styles.css
Fix #237 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/virus-scanner-for-mac
- After: https://issue-237--bitdefender--hlxsites.hlx.page/solutions/virus-scanner-for-mac
> Columns variations

- blocks/header/header.js
- scripts/breadcrumbs.js
- scripts/scripts.js
Adds support for multiple Link Tracking Regions:
Fix #267 
Test URLs:
- After: https://267-linktracker--bitdefender--hlxsites.hlx.page/solutions/
> feat: link tracker

- blocks/hero/hero.js
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/antivirus
- After: https://fix-bubble-hero--bitdefender--hlxsites.hlx.page/solutions/antivirus
> Move bubble in hero to the closets button

- .github/workflows/run-tests.yaml
Test URLs:
- After: https://update-ghost--bitdefender--hlxsites.hlx.page/solutions/
> Fail ghost inspector on screenshot comparison 

- blocks/barchart/barchart.css
Fix #199
Test URLs:
- After: https://199-barchart-issues--bitdefender--hlxsites.hlx.page/solutions/
> 199 barchart issues

- blocks/header/header.css
Fix #16 
Test URLs:
- After: https://correct-mouseleave--bitdefender--hlxsites.hlx.page/solutions/
> Correct mouse-leave animation for top-links

- blocks/products/products.js
Fix #224 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/total-security
- After: https://issue-224--bitdefender--hlxsites.hlx.page/solutions/total-security
> updated price

- blocks/columns/columns.css
Fix #291
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/premium-security
- After: https://291-column-bullet-points--bitdefender--hlxsites.hlx.page/solutions/premium-security
> column with a bullet point list

- blocks/accordion/accordion.css
Fix #284
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/vpn
- After: https://bugfix-accordion-heading--bitdefender--hlxsites.hlx.page/solutions/vpn
> Styling for h3 for accordion headings

- blocks/features/features.css
- styles/styles.css
Test URLs:
- After: https://link-accessibility-improvements--bitdefender--hlxsites.hlx.page/solutions/
> fix: accessibility improvements

- blocks/header/header.css
Test URLs:
- After: https://header-animation-fix--bitdefender--hlxsites.hlx.page/solutions/
> Header animation fix

- styles/styles.css
Fix #301 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/antivirus-free-for-android
- After: https://section-with-buttons-right-aligned--bitdefender--hlxsites.hlx.page/solutions/antivirus-free-for-android
> Align buttons on right and adapt style

- blocks/hero/hero.css
Fix #293 
Test URLs:
- After: https://hero-fix--bitdefender--hlxsites.hlx.page/solutions/
> avoided checks

- blocks/tabs/tabs.css
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.live/solutions/total-security
- After: https://bugfix-accesibility--bitdefender--hlxsites.hlx.page/solutions/total-security
> Improved accessibility of the drop-down menu

- blocks/products/products.css
- styles/styles.css
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/small-office-security
- After: https://bugfix-accesibility-blue--bitdefender--hlxsites.hlx.page/solutions/small-office-security
> Changed the accesibility of the blue background

- blocks/quote-carousel/quote-carousel.css
- scripts/scripts.js
- styles/styles.css
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/internet-securityt
- After: https://new-columnar-images--bitdefender--hlxsites.hlx.page/solutions/internet-security
> Update cta images and styling

- blocks/products/products.css
- styles/styles.css
Fix #197
Fix #286 
Fix #184 
Test URLs:
- After: https://issue-197--bitdefender--hlxsites.hlx.page/solutions/
> Product card style fixes

- blocks/hero/hero.css
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/small-office-security
- After: https://bugfix-hero-headings--bitdefender--hlxsites.hlx.page/solutions/small-office-security
> Fixed heading accesibility for hero

- blocks/columns/columns.css
- blocks/products/products.css
- styles/lazy-styles.css
- styles/styles.css
Fix #295 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/vpn
- After: https://295-vpn-download-link--bitdefender--hlxsites.hlx.page/solutions/vpn
> Add functionality for download modal

- blocks/products/products.js
Test URLs:
- After: https://seo-product-card--bitdefender--hlxsites.hlx.page/solutions/
> update link logic

- blocks/header/header.css
Test URLs:
- After: https://better-menu-bar--bitdefender--hlxsites.hlx.page/solutions/
> better menu bar

- blocks/products/products.css
Fix #309 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/vpn
- After: https://309-h4-blue-section--bitdefender--hlxsites.hlx.page/solutions/vpn
> Fix product cards H3 and H4 order

- blocks/columns/columns.css
- blocks/fragment-metadata/fragment-metadata.js
Fix #112
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/digital-identity-protection
- After: https://awards-inline-h--bitdefender--hlxsites.hlx.page/solutions/digital-identity-protection
> Awards inline h

- blocks/products/products.css
Test URLs:
- After: https://lhs-solutions--bitdefender--hlxsites.hlx.page/solutions/
> accessibility color

- blocks/product-comparison-table/product-comparison-table.css
Fix #321 
Test URLs:
- Before: https://mobile-security-for-android--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android
- After: https://issue-321--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android
> product comparison table is now responsive

- blocks/hero/hero.css
- blocks/hero/hero.js
- blocks/quote/quote.css
- blocks/quote/quote.js
- scripts/scripts.js
Fix #230 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/free
- After: https://230-hero-quote-free--bitdefender--hlxsites.hlx.page/solutions/free
> Add quotes to hero

- blocks/hero/hero.css
Fix #340
Test URLs:
- After: https://340-hero-h4-color--bitdefender--hlxsites.hlx.page/solutions/
> Hero add H4 style

- styles/styles.css
Fix #345 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/total-security
- After: https://345-space-between-buttons--bitdefender--hlxsites.hlx.page/solutions/total-security
> Add no-padding-top-bottom css class

- blocks/barchart/barchart.css
- blocks/barchart/barchart.js
- scripts/lib-franklin.js
Fix #318
Test URLs:
- After: https://issue-318--bitdefender--hlxsites.hlx.page/solutions/
> Resized images hero and Barchart

- blocks/features/features.js
Fix #316 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/total-security
- After: https://fix-316--bitdefender--hlxsites.hlx.page/solutions/total-security
> crawlable product links 

- blocks/footer/footer.css
- blocks/footer/footer.js
Fix #338 
Fix: #343 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/password-manager
- After: https://issue-338--bitdefender--hlxsites.hlx.page/solutions/password-manager
> Increased footer performance and smooth animations 

- blocks/header/header.js
Fix #350 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.live/solutions/
- After: https://404-fix--bitdefender--hlxsites.hlx.live/solutions/
To view the changes append 404 to the URL
> Fixed 404 header

- blocks/product-comparison-table/product-comparison-table.css
- blocks/product-comparison-table/product-comparison-table.js
Fix #179 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android
- After: https://add-animation-to-comparison-table--bitdefender--hlxsites.hlx.page/solutions/mobile-security-android
> Add animation to product comparison table

- blocks/accordion/accordion.css
Fix #272
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/small-office-security
- After: https://accordion-arrow--bitdefender--hlxsites.hlx.page/solutions/small-office-security
> Fixed accordion arrow

- blocks/product-comparison-table/product-comparison-table.css
Fix #352
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/premium-security
- After: https://issue-352--bitdefender--hlxsites.hlx.page/solutions/premium-security
> Product comparison table style fixes

- head.html
- scripts/scripts.js
Fix #354
Test URLs:
- After: https://354-allow-referrer--bitdefender--hlxsites.hlx.page/solutions/
> Add no-referrer-when-downgrade

- scripts/scripts.js
Fix #361 
Test URLs:
- After: https://issue-361--bitdefender--hlxsites.hlx.page/solutions/
> Fix page.attributes in "page load started" event

- blocks/products/products.css
Fix #363 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/digital-identity-protection
- After: https://363-dip-page-btn-issue--bitdefender--hlxsites.hlx.page/solutions/digital-identity-protection
> Fix text in product cards buttons

- blocks/products/products.css
Fix #368 
Test URLs:
- After: https://368-pc-size-solutions--bitdefender--bitdefender--hlxsites.hlx.page/solutions/
> Fix product cards spacing o solution

- blocks/products/products.css
Fix #375 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/password-manager
- After: https://375-password-manager-btns--bitdefender--hlxsites.hlx.page/solutions/password-manager
> Fix missalignment of buttons

- blocks/products/products.css
- blocks/products/products.js
Test URLs:
- After: https://no-undefined--bitdefender--hlxsites.hlx.page/solutions/
> Prevent undefined when discount is missing

- blocks/hero/hero.css
- blocks/product-comparison-table/product-comparison-table.css
- blocks/product-comparison-table/product-comparison-table.js
Fix #379 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/antivirus-comparison
- After: https://issue-379--bitdefender--hlxsites.hlx.page/solutions/antivirus-comparison
> Antivirus comparison page fixes

- blocks/barchart/barchart.css
- blocks/barchart/barchart.js
- scripts/breadcrumbs.js
Fix #386
Test URLs:
- After: https://fix-ui-tests-bar-chart--bitdefender--hlxsites.hlx.page/solutions/
> fix race condition for barchart icons

- blocks/image-columns/image-columns.css
- blocks/product-comparison-table/product-comparison-table.css
- scripts/scripts.js
- styles/styles.css
- styles/thank-you.css
Fix #377 
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/thank-you
- After: https://377-thank-you--bitdefender--hlxsites.hlx.page/solutions/thank-you
> Add new css for page thank-you

- solutions/blocks/products/products.js
Fix #399 
Test URLs:
- After: https://selector-not-working--bitdefender--hlxsites.hlx.page/solutions/
> fix: device selector not working

- solutions/blocks/products/products.js
Fix #407 
Test URLs:
- After: https://407-base_uri--bitdefender--hlxsites.hlx.page/solutions/
> Fix base uri

- solutions/scripts/scripts.js
Fix #401 
Test URLs:
- After: https://401-hreflang-parameter--bitdefender--hlxsites.hlx.page/solutions/
> Add hreflang

- solutions/blocks/hero/hero.css
Fix #dex-15772
Test URLs:
- After: https://dex-15772--bitdefender--hlxsites.hlx.page/solutions/
> Changed gradient color for hero black variant

- solutions/blocks/quote-carousel/quote-carousel.js
- solutions/blocks/quote/quote.js
- solutions/scripts/lib-franklin.js
- solutions/scripts/scripts.js
Fix #410 
Test URLs:
- After: https://410-svgs-issue-quote-carrousel--bitdefender--hlxsites.hlx.page/solutions/
> Fix quote-carousel & carousel not rendering

- solutions/scripts/scripts.js
Fix #DEX-15414
Test URLs:
- After: https://DEX-15414--bitdefender--hlxsites.hlx.page/solutions/
> DEX-15414 hreflang for SEO

- solutions/blocks/header/header.js
Fix #421 
Test URLs:
- After: https://421-logo-not-showing--bitdefender--hlxsites.hlx.page/solutions/
> Update header with decorateIcons for logo div

- solutions/scripts/lib-franklin.js
- solutions/scripts/scripts.js
Test URLs:
- After: https://hotfix-canonical--bitdefender--hlxsites.hlx.page/solutions/
> hotfix-revert-canonical

- solutions/blocks/hero/hero.css
Fix #DEX-16338
- added the same sizing and core design for default ( white )
- removed the teal spacing / separator from the bottom
Test URLs:
- After: https://DEX-16338--bitdefender--hlxsites.hlx.page/solutions/
> DEX-16338 - Added awards support for default banner also

- solutions/blocks/hero/hero.css
Test URLs:
- After: https://lint-fixes-hero--bitdefender--hlxsites.hlx.page/solutions/
> Lint fixes hero block

- solutions/sitemap.xml
- tools/sitemap/create.js
Test URLs:
- After: https://add-xml-declaration--bitdefender--hlxsites.hlx.page/solutions/
> Fix: Add xml declaration

- solutions/scripts/scripts.js
- solutions/sitemap.xml
- tools/sitemap/create.js
Test URLs:
- After: https://fix-hreflang-be--bitdefender--hlxsites.hlx.page/solutions/
> fix: hreflang be

- solutions/scripts/utils/utils.js
Test URLs:
- After: https://pid-hfx--bitdefender--hlxsites.hlx.page/solutions/
> PID in metadata

- solutions/scripts/analytics.js
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.live/solutions/
- After: https://default-consent-fix--bitdefender--hlxsites.hlx.live/solutions/
> feat: set default consent to in

- solutions/scripts/analytics.js
Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.live/solutions/
- After: https://event-payload-fix--bitdefender--hlxsites.hlx.live/solutions/
> fix: wrong event payload

- solutions/blocks/hero/hero.css
Test URLs:
- After: https://hero-padding--bitdefender--hlxsites.hlx.page/solutions/
> hero-padding-removal

- solutions/blocks/columns/columns.css
Test URLs:
- After: https://columns-fix--bitdefender--hlxsites.hlx.page/solutions/
> columns margin fix
